[package]
name = "zfs_object_agent"
version = "0.1.0"
authors = ["Matthew Ahrens <mahrens@delphix.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
async-stream = "0.3.0"
bincode = "1.3.2"
futures = "0.3.13"
futures-core = "0.3.13"
futures-util = "0.3.13"
more-asserts = "0.2.1"
nvpair = { git = "https://github.com/ahrens/rust-libzfs", branch = "work"}
#nvpair = { path = "../rust-libzfs/nvpair" }
#nvpair = "0.5.0"
#nvpair-sys = "0.4.0"
pin-utils = "0.1.0"
rand = "0.8.3"
#rust-s3 = { version = "0.27.0-rc1", features = ["tokio", "blocking"] }
rust-s3 = "0.27.0-rc1"
serde = { version = "1.0.125", features = ["derive"] }
tokio = { version = "1.4", features = ["full"] }
tokio-stream = "0.1.5"
#os_pipe = "0.9.2"
tokio-pipe = "0.2.1"
